In [21]:
import pandas as pd

data = pd.read_csv (r'C:\Users\wangm1\vscode\Python\dspongml\pong.csv')
data

,ball_x,ball_y,ball_vx,ball_vy,paddle_direction,paddle_y,Ball.RADIUS,Paddle.L,Paddle.STEP,WIDTH,HEIGHT,BORDER,VELOCITY,FPS
0,770,200,-12,-5,0,200,10,80,20,800,400,20,12,30
1,770,200,-12,-5,0,200,10,80,20,800,400,20,12,30
2,758,195,-12,-5,0,200,10,80,20,800,400,20,12,30
3,746,190,-12,-5,0,200,10,80,20,800,400,20,12,30
4,734,185,-12,-5,0,200,10,80,20,800,400,20,12,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2380,230,57,-12,11,0,200,10,80,20,800,400,20,12,30
2381,218,68,-12,11,0,200,10,80,20,800,400,20,12,30
2382,206,79,-12,11,0,200,10,80,20,800,400,20,12,30
2383,194,90,-12,11,0,200,10,80,20,800,400,20,12,30
2384,182,101,-12,11,0,200,10,80,20,800,400,20,12,30

In [14]:
X = data.drop('paddle_y',axis=1) 
y = data['paddle_y']

In [15]:
# split:75% train / 25% test 
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.25, random_state=0)

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)
model.fit(Xtrain, ytrain)

# Test it on test data
y_model = model.predict(Xtest)

from sklearn.metrics import accuracy_score
accuracy_score(ytest, y_model)

1.0

In [16]:
from joblib import dump, load 
dump(model, 'mymodel.joblib') #save

['mymodel.joblib']